# run all hooks with:
# pre-commit run --hook-stage manual --all
ci:
  skip:
    # pre-commit.ci doesn't have Rust installed
    - cargo-fmt
    - cargo-deny

repos:
  - repo: local
    hooks:
      - id: cargo-fmt  # rustup component add rustfmt
        name: cargo fmt
        entry: cargo fmt --all --
        language: system
        types: [rust]
        pass_filenames: false

      - id: cargo-deny  # cargo install --locked cargo-deny
        name: cargo deny
        entry: cargo deny --all-features check --
        language: system
        pass_filenames: false

      - id: cargo-check
        name: cargo check
        entry: cargo check --all-features --all-targets --
        language: system
        pass_filenames: false
        types: [rust]
        stages: [manual]  # because it's slow

      - id: cargo-clippy  # rustup component add clippy
        name: cargo clippy
        entry: cargo clippy --tests --all-features -- -D warnings
        language: system
        pass_filenames: false
        types: [rust]
        stages: [manual]  # because it's slow
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
        exclude: test/.*\.py
      - id: check-yaml
      - id: check-docstring-first
      - id: check-executables-have-shebangs
      - id: check-toml
      - id: check-added-large-files
        args: ['--maxkb=2048']
        exclude: ^logo/
      - id: detect-private-key
      - id: forbid-new-submodules
      - id: pretty-format-json
        exclude: demo.ipynb
        args: ['--autofix', '--no-sort-keys', '--indent=4']
      - id: end-of-file-fixer
      - id: mixed-line-ending

      - id: check-yaml
      - id: check-toml
      - id: end-of-file-fixer
        exclude: |
          (?x)(
              (^sysconfig/)|
              (.*\.stdout)
          )
      - id: trailing-whitespace
        exclude: |
          (?x)(
              (^sysconfig/)|
              (.*\.stdout)
          )
      - id: mixed-line-ending
  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.6
    hooks:
    - id: codespell
      additional_dependencies:
        - tomli
