import {Button, VerticalBox, StandardTableView, HorizontalBox} from "std-widgets.slint";

export component AppWindow inherits Window {
    title: "AVD Manager";

    property <length> btn-height : 32px;

    in property <[[StandardListViewItem]]> avdlist: [];

    HorizontalBox {
        table := StandardTableView {
            columns: [
                { title: "Name" },
                { title: "SDK Level" },
                { title: "Tag" },
                { title: "ABI" },
            ];
            rows: root.avdlist;
        }

        VerticalBox {
            new_btn := Button {
                text: "New";
                height: btn-height;
            }

            edit_btn := Button {
                text: "Edit";
                enabled: false;
                height: btn-height;
            }

            delete_btn := Button {
                text: "Delete";
                enabled: false;
                height: btn-height;
            }

            repair_btn := Button {
                text: "Repair";
                enabled: false;
                height: btn-height;
            }

            details_btn := Button {
                text: "Details";
                enabled: false;
                height: btn-height;
            }

            start_btn := Button {
                text: "Start";
                enabled: false;
                height: btn-height;
            }

            VerticalBox { height: btn-height * 4; }

            refresh_btn := Button {
                text: "Refresh";
                height: btn-height;
            }
        }
    }
}
